#cloud-config
autoinstall:
  version: 1 # Movido para o topo do bloco 'autoinstall'
  
  # A chave 'version: 1' foi removida do final.

  apt:
    disable_components: []
    fallback: offline-install
    geoip: true
    mirror-selection:
      primary:
      - country-mirror
      - arches: &id001
        - amd64
        - i386
        uri: http://archive.ubuntu.com/ubuntu/
      - arches: &id002
        - s390x
        - arm64
        - armhf
        - powerpc
        - ppc64el
        - riscv64
        uri: http://ports.ubuntu.com/ubuntu-ports
    preserve_sources_list: false
    security:
    - arches: *id001
      uri: http://security.ubuntu.com/ubuntu/
    - arches: *id002
      uri: http://ports.ubuntu.com/ubuntu-ports
  codecs:
    install: true
  drivers:
    install: true
  identity:
    hostname: lucas-Aspire-A314-35
    password: $6$Fl52XsYpwfzjnYG6$wzqPOtaTTKYBMJFb6ar.LHLbYQORNsEHS5C1nXQLhP9Wakm9HndraDdg9pORgwJ3IFyxoecravps72HXykWfp/
    realname: Lucas
    username: lucas
  kernel:
    package: linux-generic-hwe-24.04
  keyboard:
    layout: br
    toggle: null
    variant: ''
  locale: pt_BR.UTF-8
  network:
    ethernets: {}
    version: 2
    wifis:
      wlp0s20f3:
        access-points:
          VIVOFIBRA-0D78-5G:
            auth:
              key-management: psk
              password: 58BDD97764
            networkmanager:
              name: VIVOFIBRA-0D78-5G
              passthrough:
                ipv6.addr-gen-mode: default
                ipv6.ip6-privacy: '-1'
                proxy._: ''
                wifi-security.auth-alg: open
              uuid: f3c8eb19-893d-4af0-8806-e0be9c6b416b
        dhcp4: true
        dhcp6: true # Corrigi a indentação desta linha, pois estava errada no original.
        networkmanager:
          name: VIVOFIBRA-0D78-5G
          uuid: f3c8eb19-893d-4af0-8806-e0be9c6b416b
        renderer: NetworkManager
  oem:
    install: auto
  source:
    id: ubuntu-desktop
    search_drivers: true
  ssh:
    allow-pw: true
    authorized-keys: []
    install-server: false
  storage:
    config:
    - transport: pcie
      preserve: true
      id: nvme-controller-nvme0
      type: nvme_controller
    - ptable: gpt
      serial: HFM128GD3JX016N_CYB4N030311204K23_1
      wwn: nvme.1c5c-435942344e3033303331313230344b3233-48464d3132384744334a583031364e-00000001
      nvme_controller: nvme-controller-nvme0
      path: /dev/nvme0n1
      preserve: true
      name: ''
      grub_device: false
      id: disk-nvme0n1
      type: disk
    - device: disk-nvme0n1
      size: 536870912
      flag: boot
      number: 1
      preserve: true
      grub_device: true
      offset: 1048576
      partition_type: c12a7328-f81f-11d2-ba4b-00a0c93ec93b
      path: /dev/nvme0n1p1
      uuid: 70f08cd3-3f7f-4d48-ac58-0220ae3a3202
      id: partition-nvme0n1p1
      type: partition
    - device: disk-nvme0n1
      size: 63749226496
      flag: linux
      number: 2
      preserve: true
      grub_device: false
      offset: 537919488
      partition_type: 0fc63daf-8483-4772-8e79-3d69d8477de4
      path: /dev/nvme0n1p2
      uuid: 8edfd86f-8a7d-44af-9e29-81e37e32195e
      id: partition-nvme0n1p2
      type: partition
    - device: disk-nvme0n1
      size: 11868831744
      flag: linux
      number: 3
      preserve: true
      grub_device: false
      offset: 64287145984
      resize: true
      partition_type: 0fc63daf-8483-4772-8e79-3d69d8477de4
      path: /dev/nvme0n1p3
      uuid: 41b0751a-685d-4c99-9aba-957f8cf997cb
      id: partition-nvme0n1p3
      type: partition
    - device: disk-nvme0n1
      size: 51878297600
      wipe: superblock
      number: 4
      preserve: false
      offset: 76155977728
      path: /dev/nvme0n1p4
      id: partition-0
      type: partition
    - fstype: ext4
      volume: partition-0
      preserve: false
      id: format-0
      type: format
    - path: /
      device: format-0
      id: mount-1
      type: mount
    - fstype: vfat
      volume: partition-nvme0n1p1
      preserve: true
      id: format-partition-nvme0n1p1
      type: format
    - path: /boot/efi
      device: format-partition-nvme0n1p1
      id: mount-0
      type: mount
  timezone: America/Sao_Paulo
  ubuntu-pro:
    # Enable Ubuntu-Pro using a contract token
    # Note that the example below is an invalid contract token.
    token: C1fQ3tJ73T4TRTELLKJWBBSTEv1xV
  packages:
    - libreoffice
    - gimp
    - git
    - wget
    - vlc
    - gnome-shell-extension-manager
    - gparted
  updates: all
  shutdown: reboot

